changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - luckttery-bot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Fixed 📌
      labels:
        - enhancement
    - title: Other Changes 📝
      labels:
        - "*"
